### ISSUE TITLE
Cross platform deployment

### ISSUE THREAD

**Issue by JasonNumberThirteen** [electronstudio/jaylib#11]
Greetings, I'm very interested in this Java binding for "_raylib_". I would like to know **if there are any future plans for adding support to many platforms**, especially for Android and HTML5. If not, then at least explain how can I try to do it on my own, please. I realise it's easy to say, but much harder to do.

**Comment by electronstudio** [comment]
I have no plans beyond Windows, Mac and Linux.

I have never tried Raylib on Android myself. Assuming you have Raylib compiling and working on Android then it should be possible to add it as another platform in the config file. 

Fo HTML5, Java doesn't run on HTML5 so you would need to first solve that problem using some sort of translator. How you bind to Raylib would then depend entirely on what translator you used.

**Comment by JasonNumberThirteen** [comment]
Thanks for your reply. AFAIK, GWT is widely used for converting Java to HTML5 (eventually "CheerpJ").

http://www.gwtproject.org/
https://www.leaningtech.com/pages/cheerpj.html

**Comment by electronstudio** [comment]
I think GWT translates Java sourcecode into Javascript source code so what you would need is a Javascript binding for Raylib.

**Comment by electronstudio** [comment]
CheerpJ seems to translate Java bytecode to WASM, and Raylib can be compiled to WASM, so that sounds more promising, but I don't know enough about WASM to be sure and CheerpJ is non free so Im not inclined to experiment with it. It all seems a lot of work when there already exist far more mature cross platform Java libraries than Raylib, e.g, LibGDX.

**Comment by JasonNumberThirteen** [comment]
OK, I get it. I know there is a JavaScript binding, but I wanted to stick to Java and have one project to many platforms. Thanks for your time.

**Comment by electronstudio** [comment]
If you can figure out how to do it, go ahead. I think Android is probably much easier than HTML5 because at least Android runs the two languages involved, C and Java, and JavaCPP already supports Android.

**Comment by JasonNumberThirteen** [comment]
Alright, if I find time, I'll try to make this on my own.
