### ISSUE TITLE
Jaylib.java wont compile - defined twice - public static class Rectangle extends Raylib.Rectangle 

### ISSUE THREAD

**Issue by mores** [electronstudio/jaylib#15]
See:
https://github.com/electronstudio/jaylib/blame/master/src/com/raylib/Jaylib.java#L46
https://github.com/electronstudio/jaylib/blame/master/src/com/raylib/Jaylib.java#L61

**Comment by electronstudio** [comment]
I guess this caused by the PR the other day.  Silly me assumed that people tested their PRs at least compiled before submitting them.  Won't be so trusting in future!  https://github.com/electronstudio/jaylib/commit/c2546ad991fe6e3e072600d9a3d43108d27d46c5
