### ISSUE TITLE
Can't make a Rectangle() with four arguments.

### ISSUE THREAD

**Issue by gnevesdev** [electronstudio/jaylib#16]
It seems that the Rectangle() four arguments constructor is not working...
`
new Jaylib.Rectangle((float)0, (float)0, (float)16, (float)16);
`
That gives me an error...

**Comment by electronstudio** [comment]
What's the error?  Rectangle class was messed up and has just been fixed so this might be fixed now.

**Comment by gnevesdev** [comment]
> What's the error? Rectangle class was messed up and has just been fixed so this might be fixed now.

Well, at the Raylib Discord server, someone told me that the Rectangle class was not fixed in the releases.
And I downloaded one of the releases (the latest one) instead of compiling it myself.
I'm gonna try compiling, and see if the problem gets fixed. I really hope so 🙏🏻.
If it works, I suggest updating the releases, so people will not have that same problem anymore 🤔.

**Comment by electronstudio** [comment]
Will do a new release when Raylib 3.5 is released.

**Comment by electronstudio** [comment]
I have updated the build instructions in the README to ensure you get the compatible version of Raylib when you build.

**Comment by gnevesdev** [comment]
> I have updated the build instructions in the README to ensure you get the compatible version of Raylib when you build.

Thanks a lot!

**Comment by gnevesdev** [comment]
Now just one more thing... At this part:
`Build and install Raylib from the raylib directory`
How to do that?

**Comment by electronstudio** [comment]
https://github.com/raysan5/raylib#building-raylib-on-multiple-platforms

**Comment by gnevesdev** [comment]
Couldn't build it.. It was too complicated! Waiting for Jaylib 3.5...

**Comment by electronstudio** [comment]
Note that you can use the current version to make Rectangles.  It just doesn't have the convenient constructor found in https://github.com/electronstudio/jaylib/blob/master/src/com/raylib/Jaylib.java .  So you could copy/paste that code into your project.  Or just create the Rectangles the less convenient way.
