### ISSUE TITLE
How to choose the OpenGL version

### ISSUE THREAD

**Issue by erioxis** [electronstudio/jaylib#24]
I have an old pc that does not support newer versions of OpenGL
Can I change it?
![image](https://user-images.githubusercontent.com/61615749/125315708-0d91c080-e340-11eb-82a3-136d065411d7.png)

**Comment by electronstudio** [comment]
You would have to ask Raylib whether this is possible.  Jaylib is just a wrapper around Raylib.  Probably ask on the Raylib Discord is fastest way.

In the past I have used Mesa software drivers to get OpenGL on PCs that dont support hardware acceleration.  You could try that: https://www.google.com/search?client=firefox-b-e&q=llvmpipe+windows

**Comment by erioxis** [comment]
> You would have to ask Raylib whether this is possible.  Jaylib is just a wrapper around Raylib.  Probably ask on the Raylib Discord is fastest way.
> 
> In the past I have used Mesa software drivers to get OpenGL on PCs that dont support hardware acceleration.  You could try that: https://www.google.com/search?client=firefox-b-e&q=llvmpipe+windows

Thx, i will try this

**Comment by electronstudio** [comment]
Raylib can be compiled with OpenGL 1 see https://github.com/raysan5/raylib/wiki/FAQ

I doubt there is enough demand for that to be worth us shipping native jars compiled in this way, but it should be easy to make your own. If anyone does want them then post here.
