### ISSUE TITLE
Plans to upgrade to Raylib 4.0?

### ISSUE THREAD

**Issue by gururise** [electronstudio/jaylib#27]
Just wondering if there are plans to upgrade this awesome library to the new Raylib 4.0 base?

**Comment by electronstudio** [comment]
I've updated the source code, and built jars for Linux and Mac. Here if you want to test them:
[jar.zip](https://github.com/electronstudio/jaylib/files/7541648/jar.zip)

To do a release I first need to also build for Windows (and I would like to automate that).

**Comment by electronstudio** [comment]
did a windows build: [jaylibwindows.zip](https://github.com/electronstudio/jaylib/files/7559190/jaylibwindows.zip)
would be useful if anyone let me know it works.

still not automated though
