### ISSUE TITLE
DrawTextEx takes a vector and not a font

### ISSUE THREAD

**Issue by YeffyCodeGit** [electronstudio/jaylib#33]
Im trying to draw some text with a custom font, but it looks like DrawTextEx takes in a vector2 where it should take a font.

**Comment by electronstudio** [comment]
Javadoc says it takes a font:

static void DrawTextEx​(Raylib.Font font, String text, Raylib.Vector2 _position, float fontSize, float spacing, Raylib.Color tint)

If it doesn't work then please provide an example program and the output when you compile it.

**Comment by YeffyCodeGit** [comment]
Oh yeah, that works! I was looking at what intellij was saying in its autocomplete, must have been a bug. Thanks!
