### ISSUE TITLE
Load a Texture2D from this.getClass().getResource()?

### ISSUE THREAD

**Issue by glowiak** [electronstudio/jaylib#37]
In all of the examples of Jaylib I see all the Texture2Ds being loaded from local files.

Is there any way to use this.getClass().getResource() with this?

Because distributing a game in a single jarfile is much more convinient than having to have a resources directory.

**Comment by electronstudio** [comment]
Raylib doesn’t support loading from jar files, so Jaylib doesn’t support it. To do this you would have to extract the resource from the jar and save it to a temporary file on the file system, then load that. I recall I wrote code to do this in another project, sdl2gdx. 

Alternatively I think Raylib has its own format for packing resources into an archive and functions to support loading them from there.

**Comment by glowiak** [comment]
Hell bye Jaylib.

I will search for a graphics library that supports loading from jars.

**Comment by electronstudio** [comment]
For the majority of purposes a native Java library like LibGDX is going to be better suited than Jaylib, so I wouldn’t advocate anyone to use Jaylib. But this issue has a workaround, as mentioned, and the work around is only about 5 lines of code, so it shouldn’t be relevant to the decision at all.

**Comment by glowiak** [comment]
@electronstudio But libgdx is bloated and overcomplicated.

Extracting the jarfile is not an option either. I am working on a plugin, basically a rewrite of RL's texture loading code with getResource() additions.

Wish me luck.
