### ISSUE TITLE
Raylib header conflicts when compiling on Windows

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/jaylib#4]
Raylib function names conflict with Windows function names.  Raylib have declined the request to add a prefix or change their function names: https://github.com/raysan5/raylib/issues/896

As a work around I have hacked the Windows headers to remove the conflicting funtions: https://github.com/electronstudio/jaylib/tree/master/raylib_bug_896_hack

Less hacky solutions welcome!

**Comment by Triangle345** [comment]
I can reproduce this every time on windows while using something like doctest with raylib.

`
#include <Doctest/doctest.h>
`

**Comment by electronstudio** [comment]
Thanks @Triangle345 , I have used that.  I also had to add VC_EXTRALEAN and WIN32_LEAN_AND_MEAN to get it work!
