### ISSUE TITLE
Why `LoadImageColors` returns `Color` instead of `Color[]`?

### ISSUE THREAD

**Issue by xzripper** [electronstudio/jaylib#52]
Raylib cheatsheet:
```c
Color *LoadImageColors(Image image); // Load color data from image as a Color array (RGBA - 32bit)
```

Java:
```java
public static native Raylib.Color LoadImageColors(@ByVal Raylib.Image var0);
```

And same issue with `LoadMaterials`, `LoadRandomSequence`, etc...

Why Jaylib returns single object instead of array?

**Comment by electronstudio** [comment]
Google "array to pointer decay".

The C function doesn't return an array - it returns a pointer.  The pointer *may* point to an array, or it may point to a single struct.  The compiler has no way to know from that function definition.

If we know that it has indeed returned an array, then we can access the other elements with https://electronstudio.github.io/jaylib/com/raylib/Raylib.Color.html#position(long)

**Comment by electronstudio** [comment]
https://github.com/electronstudio/jaylib?tab=readme-ov-file#arrays

**Comment by xzripper** [comment]
Thanks!
