### ISSUE TITLE
Publish on maven repo

### ISSUE THREAD

**Issue by electronstudio** [electronstudio/jaylib#6]
Publishing on Jitpack is quite easy, but since I'm not using this project for anything yet I haven't done it.  JCentral would be better but is perhaps more work.

**Comment by mores** [comment]
Would you like some help in getting this published to a maven repo ?

**Comment by Ewpratten** [comment]
This would save me so much work when I use this library. I only have experience setting up JitPack for Gradle projects though, so I will not be able to make a good PR for this.

You could also look into using the GitHub Packages Repository, which allows you to publish JARs via `curl` if you really wanted

**Comment by Ewpratten** [comment]
On second thought, I'm going to look in to making a PR for this

**Comment by electronstudio** [comment]
Plan for this:

- [ ] Upload current jars to Cloudsmith repo
- [ ] Make video showing beginners how to use them
- [ ] Switch (as much of build as possible, doesnt have to be all at once) to use Maven
- [ ] Sign up for Maven Central
- [ ] Produce Javadoc jar (can we extract the doc strings from raylib.h ?)
- [ ] Use Maven to publish on Maven Central

**Comment by rutenkolk** [comment]
The `4.0.+` version as used in the gradle example project does not work in maven as maven does not support version ranges the way gradle does (the maven example still sits on version 3.7.0). Maybe display the `4.0.0-0` version more prominently somewhere. 

There are more tools like leiningen which [while allowing ranges, warn you heavily when you do](https://github.com/technomancy/leiningen/issues/734). Leiningen for example is the most prominent build-tool in clojure, which makes this version of the library somewhat inaccasible for the clojure programming language. I would wager most leiningen users have never touched version ranges.

**Comment by rutenkolk** [comment]
Maybe display the `4.0.0-0` version more prominently somewhere. 

There are more tools like leiningen which [while allowing ranges, warn you heavily when you do](https://github.com/technomancy/leiningen/issues/734). Leiningen for example is the most prominent build-tool in clojure, which makes this version of the library somewhat inaccasible for the clojure programming language. I would wager most leiningen users have never touched version ranges.

**Comment by electronstudio** [comment]
Version number is displayed under releases, not sure where else anyone would look for it. 

For Gradle I suggest using 4.0.+ because if I put out at 4.0.0.1 (or if Raylib upstream does a 4.0.1) then it will be a bug fix release and I assume most people would want it immediately. I wouldn’t suggest using 4.+ because Raylib API is not backwards compatible so you probably won’t want your project to change to Raylib 4.1 unexpectedly. 

Users are free to use whatever tools and ranges they like of course.

**Comment by rutenkolk** [comment]
whoops. My bad. I didn't see the releases page :woman_facepalming: 

I just read the readme.

**Comment by electronstudio** [comment]
Not fully automated, but now publishing on maven central.
