### ISSUE TITLE
include raygui (RayLib GUI) and physac

### ISSUE THREAD

**Issue by XiaochuanWang** [electronstudio/jaylib#8]
When testing the Jaylib jar, I realized that the "physac" in not in jar, and this is included in the RayLib 3.0 as its "default" 2D physics engine/component. I think it would quite useful if it (physac.h) can be included in the Jaylib jar.

similar reason for the "raygui.h"  

many thanks

**Comment by XiaochuanWang** [comment]
Additionally, some "low" level functions are missing, which mainly from the "rlgl.h". 
because of this, the official example "rlgl solar system" in the example page can't be replicated with the Jaylib jar

**Comment by uSources** [comment]
Totally agree with @XiaochuanWang , if u have some time to add physac and raygui bindings it would be awesome.

Amazing work, Thanks @electronstudio !

**Comment by Airbus5717** [comment]
anybody working on it ? 🤔

**Comment by electronstudio** [comment]
I added support for RLGL (and Raylib 3.1-dev).

With physac.h I can't get javacpp to process the mess of defines and typedefs.  No idea how C coders live with this stuff.

**Comment by electronstudio** [comment]
I got physac.h to work, but I had to change a lot of typedefs.  Not entirely happy shipping that because it's not automated and will have to be re-done for each release of physac.

**Comment by electronstudio** [comment]
raygui is added.

**Comment by electronstudio** [comment]
Physac is now deprecated by Raylib so I will leave the existing version for as long as it compiles but no-one should be using it for new projects.
